language: java
jdk: oraclejdk8
install: true
script: mvn clean install
cache:
        directories:
            - $HOME/.m2
sudo: false
script: "mvn cobertura:cobertura"
after_success:
      - bash <(curl -s https://codecov.io/bash)
